pub mod manager_create;
pub mod manager_destroy;
pub mod manager_view;
pub mod manager_view_acocunt;
pub mod manager_view_funds;
pub mod manager_view_params;
pub mod my_account_deposit;
pub mod my_account_view;
pub mod my_account_withdraw;